version: '3.8'

services:
  quotemanager.api:
    build:
      context: .
      dockerfile: QuoteManager.API/Dockerfile
    container_name: quotemanager_api
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - quotemanager-net
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - Jwt__Key=${Jwt__Key}
      - Jwt__Issuer=${Jwt__Issuer}
      - Jwt__Audience=${Jwt__Audience}
    env_file:
      - .env

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_dev
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    networks:
      - quotemanager-net

networks:
  quotemanager-net:
    driver: bridge